// Generated by Wrangler on Sun Oct 20 2024 16:14:15 GMT+1100 (Australian Eastern Daylight Time)
// by running `wrangler types`

interface Env {
	GITHUB_CLIENT_ID: string;
	GITHUB_CLIENT_SECRET: string;
	COOKIE_SESSION_SECRET: string;
	STATUS_DB: D1Database;
}
