// Generated by Wrangler on Sun Oct 20 2024 14:28:46 GMT+1100 (Australian Eastern Daylight Time)
// by running `wrangler types`

interface Env {
  GITHUB_CLIENT_SECRET: string;
  GITHUB_CLIENT_ID: string;
  COOKIE_SESSION_SECRET: string;
	STATUS_DB: D1Database;
}
